name: clean_architecture
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  fade_shimmer: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  get_it: ^7.6.7
  http: ^1.2.0
  hydrated_bloc: ^9.1.3
  intl: ^0.18.0
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.6
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
